export const herbsData = [
  { name: "Lavender", properties: "Peace, protection, love, purification, sleep", lore: "Ancient Romans used lavender in baths for purification. Associated with the Virgin Mary in medieval times.", deity: "Hecate, Circe", uses: "Burn for peaceful sleep, add to love sachets, use in purification baths" },
  { name: "Rosemary", properties: "Protection, memory, love, mental clarity, purification", lore: "Greeks wore rosemary garlands for memory during exams. Placed in coffins for remembrance.", deity: "Virgin Mary, Aphrodite", uses: "Burn for protection, carry for memory enhancement, add to love spells" },
  { name: "Sage", properties: "Wisdom, protection, cleansing, longevity, wishes", lore: "Native Americans use white sage for smudging. Romans called it 'herba sacra' (sacred herb).", deity: "Zeus, Jupiter", uses: "Burn to cleanse negative energy, carry for wisdom, use in healing rituals" },
  { name: "Mugwort", properties: "Psychic powers, protection, prophetic dreams, astral projection", lore: "Named for the moon goddess Artemis. Medieval travelers placed it in shoes for endurance.", deity: "Artemis, Diana", uses: "Burn before divination, place under pillow for prophetic dreams, carry for protection during travel" },
  { name: "Chamomile", properties: "Money, sleep, love, purification, luck", lore: "Ancient Egyptians dedicated it to the sun god Ra. Used in gambling luck spells.", deity: "Ra, Cernunnos", uses: "Wash hands before gambling, add to prosperity spells, drink for peaceful sleep" },
  { name: "Basil", properties: "Love, wealth, protection, flying, exorcism", lore: "In Italy, basil represents love. In India, it's sacred to Vishnu and Krishna.", deity: "Vishnu, Krishna, Erzulie", uses: "Carry for wealth, add to love sachets, use in protection baths" },
  { name: "Thyme", properties: "Courage, healing, sleep, psychic powers, purification", lore: "Knights wore thyme scarves for courage. Greeks burned it in temples.", deity: "Ares, Faeries", uses: "Burn for purification, wear for courage, use in healing spells" },
  { name: "Mint", properties: "Money, healing, travel protection, exorcism, lust", lore: "Named after nymph Mentha. Romans wore mint crowns at feasts.", deity: "Pluto, Hecate", uses: "Carry for money, rub on objects for healing, use in travel protection" },
  { name: "Cinnamon", properties: "Spirituality, success, healing, power, psychic powers", lore: "Ancient Egypt used cinnamon in embalming. Symbol of wealth in biblical times.", deity: "Aphrodite, Venus", uses: "Burn for spirituality, add to prosperity spells, use in healing incense" },
  { name: "Bay Laurel", properties: "Protection, psychic powers, healing, purification, strength", lore: "Oracle of Delphi chewed bay leaves for prophecy. Victory wreaths for Roman emperors.", deity: "Apollo, Aesculapius", uses: "Burn for visions, write wishes on leaves and burn, wear for protection" },
  { name: "Yarrow", properties: "Courage, love, psychic powers, exorcism", lore: "Achilles used yarrow to heal soldiers' wounds. Used in I Ching divination.", deity: "Achilles, Hermes", uses: "Hold while doing divination, use in love spells, carry for courage" },
  { name: "Nettle", properties: "Protection, healing, lust, exorcism", lore: "Vikings believed nettle protected against lightning. Used in folk medicine for centuries.", deity: "Thor, Mars", uses: "Scatter for protection, use in healing baths, carry for courage" },
  { name: "Dandelion", properties: "Divination, wishes, calling spirits, psychic powers", lore: "Blowing seeds grants wishes. Root tea enhances psychic abilities.", deity: "Hecate", uses: "Blow seeds for wishes, drink root tea before divination, bury near house for luck" },
  { name: "Rose", properties: "Love, psychic powers, healing, luck, protection", lore: "Sacred to Aphrodite. Red roses grew from Adonis's blood. Symbol of secrecy (sub rosa).", deity: "Aphrodite, Venus, Isis", uses: "Add to love spells, drink rose water for psychic powers, use petals in healing" },
  { name: "Jasmine", properties: "Love, money, prophetic dreams, spirituality", lore: "In India, jasmine represents hope and divine love. Called 'moonlight of the grove'.", deity: "Vishnu, Diana", uses: "Burn for prophetic dreams, carry for love attraction, use in prosperity spells" },
  { name: "Elderflower", properties: "Protection, healing, prosperity, sleep, exorcism", lore: "Elder Mother spirit lives in elder trees. Fairy dwelling. Never burn elder wood.", deity: "Holda, Venus, Hel", uses: "Hang over doors for protection, use in healing rituals, scatter for blessings" },
  { name: "Vervain", properties: "Love, protection, purification, peace, money, youth", lore: "Druids' sacred herb. Used to anoint altars. Romans used in treaties.", deity: "Cerridwen, Mars, Venus", uses: "Burn for love spells, carry for protection, use in purification" },
  { name: "St. John's Wort", properties: "Health, protection, strength, love, divination, happiness", lore: "Harvested on Midsummer's Eve. Protects against evil spirits and lightning.", deity: "Sun gods, Baldur", uses: "Hang for protection, carry for strength, burn at Midsummer" },
  { name: "Valerian", properties: "Love, sleep, purification, protection", lore: "Called 'all-heal' in medieval times. Pied Piper used it to lure rats.", deity: "Mercury", uses: "Add to love sachets, use in sleep pillows, hang for protection" },
  { name: "Wormwood", properties: "Psychic powers, protection, love, calling spirits", lore: "Key ingredient in absinthe. Named after Artemis. Used in astral projection.", deity: "Artemis, Diana", uses: "Burn for psychic powers, carry for protection, use in spirit work" },
  { name: "Calendula", properties: "Protection, prophetic dreams, legal matters, psychic powers", lore: "Called 'Mary's gold' - dedicated to the Virgin. Follows the sun.", deity: "Sun gods", uses: "Add to dream pillows, use in court case work, scatter for protection" },
  { name: "Echinacea", properties: "Strengthening spells, offerings, healing", lore: "Native American medicine for snake bites and infections. Called purple coneflower.", deity: "Great Spirit", uses: "Use in healing spells, add to offerings, carry for strength" },
  { name: "Lemon Balm", properties: "Love, success, healing, psychic development", lore: "Bees are attracted to it - associated with honey and sweetness.", deity: "Diana, Artemis", uses: "Add to love baths, carry for success, drink for psychic development" },
  { name: "Hyssop", properties: "Purification, protection, healing", lore: "Biblical purification herb. Used in exorcisms. Cleanses sacred spaces.", deity: "Various", uses: "Add to purification baths, hang for protection, use in cleansing rituals" },
  { name: "Comfrey", properties: "Safety during travel, money, healing", lore: "Called 'knitbone' for healing fractures. Travelers carried it for safety.", deity: "Saturn", uses: "Carry for travel safety, use in money spells, add to healing work" },
  { name: "Fennel", properties: "Protection, healing, purification, courage", lore: "Romans ate fennel for courage. Hung over doors at Midsummer for protection.", deity: "Dionysus, Prometheus", uses: "Hang for protection, eat for courage, use in healing teas" },
  { name: "Catnip", properties: "Cat magic, love, beauty, happiness", lore: "Sacred to Bast and Sekhmet. Creates bond with cats. Used in love sachets.", deity: "Bast, Sekhmet", uses: "Give to cats for bonding, carry for love, use in beauty spells" },
  { name: "Ginger", properties: "Love, money, success, power, healing", lore: "Sacred in many Asian cultures. Used in prosperity magic. Adds power to spells.", deity: "Mars", uses: "Add to spells for power boost, use in money magic, carry for success" },
  { name: "Clove", properties: "Protection, exorcism, love, money", lore: "Traded as valuable as gold. Used in oranges (pomanders) for protection.", deity: "Jupiter", uses: "Burn for protection, carry in wallet for money, add to love sachets" },
  { name: "Frankincense", properties: "Protection, exorcism, spirituality, purification", lore: "Gift to baby Jesus. Used in temples worldwide. Elevates vibration.", deity: "Ra, Baal", uses: "Burn for purification, use in meditation, add to protection incense" },
  { name: "Myrrh", properties: "Protection, exorcism, healing, spirituality", lore: "Used in Egyptian embalming. Gift of the Magi. Sacred funeral herb.", deity: "Isis, Adonis, Ra", uses: "Burn for purification, use in healing rituals, combine with frankincense" },
  { name: "Dragon's Blood", properties: "Love, protection, exorcism, potency", lore: "Resin from dragon tree. Said to be blood of dragons and elephants.", deity: "Mars", uses: "Add to any spell for power, burn for protection, use in love magic" },
  { name: "Patchouli", properties: "Money, fertility, lust, protection", lore: "Victorian era fabric protector. 1960s counterculture symbol.", deity: "Saturn", uses: "Carry for money, use in fertility magic, add to lust spells" },
  { name: "Sandalwood", properties: "Protection, wishes, healing, exorcism, spirituality", lore: "Sacred in Hindu and Buddhist traditions. Used in funeral pyres.", deity: "Vishnu, Buddha", uses: "Burn for meditation, use in healing, write wishes on sandalwood" },
  { name: "Cedar", properties: "Healing, purification, money, protection", lore: "Sacred to many Native American tribes. Temple of Solomon built with cedar.", deity: "Artemis, Persephone", uses: "Burn for purification, carry for money, use in healing ceremonies" },
  { name: "Juniper", properties: "Protection, anti-theft, love, exorcism, health", lore: "Burned to ward off plague. Protected against evil spirits and witches.", deity: "Astarte, various", uses: "Hang for protection, burn to banish negativity, carry for health" },
  { name: "Angelica", properties: "Protection, exorcism, healing, visions", lore: "Angel revealed its healing powers during plague. Called 'root of the Holy Ghost'.", deity: "Angels, Venus", uses: "Carry for protection, use in exorcism, add to vision work" },
  { name: "Mandrake", properties: "Protection, love, money, fertility, health", lore: "Human-shaped root. Said to scream when pulled. Powerful magical herb.", deity: "Hecate, Hathor, Aphrodite", uses: "Use in protection magic, carry for fertility, add to love spells" },
  { name: "Belladonna", properties: "Astral projection, visions (highly toxic - do not consume)", lore: "Witches' flying ointment ingredient. Name means 'beautiful lady'.", deity: "Hecate, Circe, Bellona", uses: "Used only symbolically or homeopathically - POISONOUS" },
  { name: "Wolfsbane", properties: "Protection, invisibility (highly toxic)", lore: "Werewolf ward. Hecate's plant. Used against shapeshifters.", deity: "Hecate", uses: "Used only symbolically - POISONOUS" },
  { name: "Hemlock", properties: "Astral projection, protection (highly toxic)", lore: "Killed Socrates. Associated with dark magic and spirits.", deity: "Hecate", uses: "Used only symbolically - POISONOUS" },
  { name: "Hawthorn", properties: "Fertility, happiness, protection from evil, fishing magic", lore: "Sacred to fairies. May Day celebrations. Never bring indoors.", deity: "Cardea, Flora, Hymen", uses: "Plant for protection, use in fertility magic, carry for happiness" },
  { name: "Oak", properties: "Protection, health, money, healing, potency, fertility, luck", lore: "Sacred to Druids. Lightning attracts to oak. Acorns for fertility.", deity: "Zeus, Jupiter, Thor, Dagda", uses: "Carry acorns for health, use oak in protection, burn for healing" },
  { name: "Willow", properties: "Love, divination, protection, healing", lore: "Moon tree. Weeping willow associated with grief and healing.", deity: "Artemis, Hecate, Persephone", uses: "Use in love magic, carry for protection, use in moon rituals" },
  { name: "Rowan", properties: "Psychic powers, healing, protection, power, success", lore: "Sacred to Druids. Protection against enchantment. Rune staves made from rowan.", deity: "Thor, Brigid", uses: "Carry for protection, use in divination, plant near home" },
  { name: "Holly", properties: "Protection, anti-lightning, luck, dream magic", lore: "Sacred at Yule. Druids wore holly. Protects against evil spirits.", deity: "Holly King, Tannus", uses: "Decorate at Yule, use in dream magic, plant for protection" },
  { name: "Ivy", properties: "Protection, healing, fidelity, love", lore: "Sacred to Dionysus. Symbol of eternal life. Binding in handfasting.", deity: "Dionysus, Bacchus, Osiris", uses: "Use in fidelity spells, carry for protection, use in love binding" },
  { name: "Mistletoe", properties: "Protection, love, hunting, fertility, health, exorcism", lore: "Druids' sacred plant. Never touches earth. Kissing tradition.", deity: "Apollo, Freya, Frigga", uses: "Hang for protection, use in love spells, carry for fertility" },
  { name: "Aloe Vera", properties: "Protection, luck, healing, love", lore: "Cleopatra's beauty secret. Egyptian funeral offering. Called 'plant of immortality'.", deity: "Venus, Moon goddesses", uses: "Grow for protection, use in healing magic, add to love spells" }
];

export const getHerbByName = (name) => herbsData.find(h => h.name.toLowerCase() === name.toLowerCase());

// Herb images — accurate per plant
const herbImages = {
  "Lavender": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/lavender/Untitled.png",
  "Rosemary": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/rosemary/rosemary.png",
  "Sage": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/sage/Untitled.png",
  "Mugwort": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/mugwortherb/mugwort.png",
  "Chamomile": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/chamomileherb/chamomile.png",
  "Basil": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/basilherb/basil.png",
  "Thyme": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/thyme/herbsthyme.png",
  "Mint": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/mint/itsmint.png",
  "Cinnamon": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/cinnamon/cinnamons.png",
  "Bay Laurel": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/bayleaf/baylaurel.png",
  "Yarrow": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/yarrow/yarrows.png",
  "Nettle": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/nettle/nettlesting.png",
  "Dandelion": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/dandelion/wishing.png",
  "Rose": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/roses/rose.png",
  "Jasmine": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/jasmine/jasmineflower.png",
  "Elderflower": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/elderflowers/elderflower.png",
  "Vervain": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/vervains/vervain.png",
  "St. John's Wort": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/stjohnswort/st+johns+wort.png",
  "Valerian": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/valerian/valarian.png",
  "Wormwood": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/wormwoods/wormwood.png",
  "Calendula": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/calendula/calendula.png",
  "Echinacea": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/echinaceaherb/theeherb.png",
  "Lemon Balm": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/lemonbalms/lemonbalm.png",
  "Hyssop": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/hyssops/hyssop.png",
  "Comfrey": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/comfreys/comfrey.png",
  "Fennel": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/fennel/fennelherb.png",
  "Catnip": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/catnip/Untitled.png",
  "Ginger": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/ginger/Untitled.png",
  "Clove": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/clove/cloves.png",
  "Frankincense": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/frankincense/Untitled.png",
  "Myrrh": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/myrrh/Untitled.png",
  "Dragon's Blood": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/dragons+blood/Untitled.png",
  "Patchouli": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/patchouli/Untitled.png",
  "Sandalwood": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/sandalwood/sandalwoods.png",
  "Cedar": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/cedar/cedarsmudge.png",
  "Juniper": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/juniper/junipers.png",
  "Angelica": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/angelicatree/angelica.png",
  "Mandrake": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/mandrake/mandrakeroot.png",
  "Belladonna": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/belladonnaplant/belladonna.png",
  "Wolfsbane": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/wolfsbane/Untitled.png",
  "Hemlock": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/hemlock/hemlocks.png",
  "Hawthorn": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/hawthrons/hawthorn.png",
  "Oak": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/oak/oakleaves.png",
  "Willow": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/willowleaves/willow.png",
  "Rowan": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/rowans/rowan.png",
  "Holly": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/hollys/holly.png",
  "Ivy": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/ivyplant/ivy.png",
  "Mistletoe": "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/mistletoe/mistletoereal.png",
  "Aloe Vera": "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69894b94180b4131b2f82c0b/d7aff3c08_aloe.png"
};

export const getHerbImage = (name) => herbImages[name] || "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&fit=crop";