export const zodiacSigns = [
  { name: "Aries", symbol: "♈", dates: "March 21 - April 19", element: "Fire", modality: "Cardinal", polarity: "Masculine", ruler: "Mars", archetype: "The Warrior", soul: "The pioneering soul that initiates, leads, and blazes new trails. Aries embodies raw courage, independence, and the primal life force that pushes through obstacles.", traits: ["Courageous", "Determined", "Confident", "Enthusiastic", "Optimistic", "Honest", "Passionate"], shadow: ["Impatient", "Aggressive", "Impulsive", "Short-tempered"] },
  { name: "Taurus", symbol: "♉", dates: "April 20 - May 20", element: "Earth", modality: "Fixed", polarity: "Feminine", ruler: "Venus", archetype: "The Builder", soul: "The grounded soul that creates lasting value and beauty. Taurus embodies patience, sensuality, and the determination to manifest heaven on earth.", traits: ["Reliable", "Patient", "Practical", "Devoted", "Responsible", "Stable"], shadow: ["Stubborn", "Possessive", "Uncompromising", "Materialistic"] },
  { name: "Gemini", symbol: "♊", dates: "May 21 - June 20", element: "Air", modality: "Mutable", polarity: "Masculine", ruler: "Mercury", archetype: "The Messenger", soul: "The curious soul that connects ideas and people. Gemini embodies adaptability, wit, and the eternal student seeking to understand life through communication.", traits: ["Gentle", "Affectionate", "Curious", "Adaptable", "Quick-witted", "Versatile"], shadow: ["Nervous", "Inconsistent", "Indecisive", "Superficial"] },
  { name: "Cancer", symbol: "♋", dates: "June 21 - July 22", element: "Water", modality: "Cardinal", polarity: "Feminine", ruler: "Moon", archetype: "The Mother", soul: "The nurturing soul that creates emotional sanctuary. Cancer embodies intuition, protection, and the deep well of feeling that connects us to our roots.", traits: ["Tenacious", "Highly imaginative", "Loyal", "Emotional", "Sympathetic", "Persuasive"], shadow: ["Moody", "Pessimistic", "Suspicious", "Manipulative"] },
  { name: "Leo", symbol: "♌", dates: "July 23 - August 22", element: "Fire", modality: "Fixed", polarity: "Masculine", ruler: "Sun", archetype: "The King/Queen", soul: "The radiant soul that expresses authentic creativity. Leo embodies self-expression, generosity, and the warm-hearted leadership that inspires others to shine.", traits: ["Creative", "Passionate", "Generous", "Warm-hearted", "Cheerful", "Humorous"], shadow: ["Arrogant", "Stubborn", "Self-centered", "Lazy", "Inflexible"] },
  { name: "Virgo", symbol: "♍", dates: "August 23 - September 22", element: "Earth", modality: "Mutable", polarity: "Feminine", ruler: "Mercury", archetype: "The Healer", soul: "The analytical soul that seeks perfection through service. Virgo embodies discernment, healing, and the sacred work of improving life through attention to detail.", traits: ["Loyal", "Analytical", "Kind", "Hardworking", "Practical", "Modest"], shadow: ["Shyness", "Worry", "Overly critical", "All work and no play"] },
  { name: "Libra", symbol: "♎", dates: "September 23 - October 22", element: "Air", modality: "Cardinal", polarity: "Masculine", ruler: "Venus", archetype: "The Diplomat", soul: "The harmonizing soul that seeks balance and beauty. Libra embodies grace, partnership, and the pursuit of justice through relating to others.", traits: ["Cooperative", "Diplomatic", "Gracious", "Fair-minded", "Social", "Idealistic"], shadow: ["Indecisive", "Avoids confrontations", "Self-pity", "People-pleasing"] },
  { name: "Scorpio", symbol: "♏", dates: "October 23 - November 21", element: "Water", modality: "Fixed", polarity: "Feminine", ruler: "Pluto (traditional: Mars)", archetype: "The Transformer", soul: "The intense soul that seeks truth through transformation. Scorpio embodies depth, power, and the courage to face the shadow and emerge reborn.", traits: ["Resourceful", "Brave", "Passionate", "Stubborn", "A true friend", "Magnetic"], shadow: ["Distrusting", "Jealous", "Secretive", "Violent tendencies"] },
  { name: "Sagittarius", symbol: "♐", dates: "November 22 - December 21", element: "Fire", modality: "Mutable", polarity: "Masculine", ruler: "Jupiter", archetype: "The Explorer", soul: "The adventurous soul that seeks wisdom through experience. Sagittarius embodies optimism, philosophy, and the quest for meaning beyond the horizon.", traits: ["Generous", "Idealistic", "Great sense of humor", "Adventurous", "Philosophical"], shadow: ["Promises more than can deliver", "Very impatient", "Will say anything", "Tactless"] },
  { name: "Capricorn", symbol: "♑", dates: "December 22 - January 19", element: "Earth", modality: "Cardinal", polarity: "Feminine", ruler: "Saturn", archetype: "The Elder", soul: "The ambitious soul that builds legacy through discipline. Capricorn embodies responsibility, mastery, and the patient climb toward lasting achievement.", traits: ["Responsible", "Disciplined", "Self-control", "Good managers", "Traditional"], shadow: ["Know-it-all", "Unforgiving", "Condescending", "Expecting the worst"] },
  { name: "Aquarius", symbol: "♒", dates: "January 20 - February 18", element: "Air", modality: "Fixed", polarity: "Masculine", ruler: "Uranus (traditional: Saturn)", archetype: "The Visionary", soul: "The innovative soul that serves humanity's evolution. Aquarius embodies originality, humanitarian ideals, and the vision of a better collective future.", traits: ["Progressive", "Original", "Independent", "Humanitarian", "Intellectual"], shadow: ["Runs from emotional expression", "Temperamental", "Uncompromising", "Aloof"] },
  { name: "Pisces", symbol: "♓", dates: "February 19 - March 20", element: "Water", modality: "Mutable", polarity: "Feminine", ruler: "Neptune (traditional: Jupiter)", archetype: "The Mystic", soul: "The compassionate soul that dissolves boundaries to connect with the divine. Pisces embodies intuition, artistry, and the transcendence of the material world.", traits: ["Compassionate", "Artistic", "Intuitive", "Gentle", "Wise", "Musical"], shadow: ["Fearful", "Overly trusting", "Sad", "Desire to escape reality", "Victim mentality"] }
];

export const planets = [
  { name: "Sun", symbol: "☉", meaning: "Core identity, ego, vitality, life purpose", rules: "Leo", represents: "The conscious self, willpower, and creative expression" },
  { name: "Moon", symbol: "☽", meaning: "Emotions, instincts, subconscious, nurturing", rules: "Cancer", represents: "Inner emotional world, habits, and how we seek comfort" },
  { name: "Mercury", symbol: "☿", meaning: "Communication, intellect, learning, travel", rules: "Gemini, Virgo", represents: "How we think, process information, and express ideas" },
  { name: "Venus", symbol: "♀", meaning: "Love, beauty, values, attraction, pleasure", rules: "Taurus, Libra", represents: "What we find beautiful, how we love, and our relationship style" },
  { name: "Mars", symbol: "♂", meaning: "Action, energy, desire, aggression, courage", rules: "Aries (traditional: Scorpio)", represents: "How we assert ourselves, pursue goals, and express anger" },
  { name: "Jupiter", symbol: "♃", meaning: "Expansion, luck, wisdom, abundance, philosophy", rules: "Sagittarius (traditional: Pisces)", represents: "Where we seek growth, meaning, and good fortune" },
  { name: "Saturn", symbol: "♄", meaning: "Discipline, structure, responsibility, karma, time", rules: "Capricorn (traditional: Aquarius)", represents: "Life lessons, limitations, and mastery through effort" },
  { name: "Uranus", symbol: "♅", meaning: "Innovation, rebellion, sudden change, freedom", rules: "Aquarius", represents: "Where we seek freedom and express individuality" },
  { name: "Neptune", symbol: "♆", meaning: "Dreams, intuition, spirituality, illusion, compassion", rules: "Pisces", represents: "Spiritual connection, imagination, and transcendence" },
  { name: "Pluto", symbol: "♇", meaning: "Transformation, power, death/rebirth, the shadow", rules: "Scorpio", represents: "Deep transformation, hidden power, and regeneration" }
];

export const houses = [
  { number: 1, name: "First House", theme: "House of Self", rules: "Self-image, appearance, first impressions, physical body, beginnings, how others see you", naturalSign: "Aries" },
  { number: 2, name: "Second House", theme: "House of Value", rules: "Money, possessions, self-worth, values, material security, personal resources", naturalSign: "Taurus" },
  { number: 3, name: "Third House", theme: "House of Communication", rules: "Communication, siblings, short trips, early education, neighbors, daily environment", naturalSign: "Gemini" },
  { number: 4, name: "Fourth House", theme: "House of Home", rules: "Home, family, roots, mother/nurturing parent, emotional foundation, ancestry, end of life", naturalSign: "Cancer" },
  { number: 5, name: "Fifth House", theme: "House of Pleasure", rules: "Creativity, romance, children, fun, self-expression, gambling, hobbies, joy", naturalSign: "Leo" },
  { number: 6, name: "Sixth House", theme: "House of Health", rules: "Health, daily routines, work, service, pets, coworkers, self-improvement", naturalSign: "Virgo" },
  { number: 7, name: "Seventh House", theme: "House of Partnership", rules: "Marriage, partnerships, contracts, open enemies, one-on-one relationships", naturalSign: "Libra" },
  { number: 8, name: "Eighth House", theme: "House of Transformation", rules: "Death, rebirth, shared resources, inheritance, sexuality, occult, deep psychology", naturalSign: "Scorpio" },
  { number: 9, name: "Ninth House", theme: "House of Philosophy", rules: "Higher education, long journeys, philosophy, religion, publishing, foreign cultures, wisdom", naturalSign: "Sagittarius" },
  { number: 10, name: "Tenth House", theme: "House of Career", rules: "Career, public image, reputation, authority, father/authority parent, achievements", naturalSign: "Capricorn" },
  { number: 11, name: "Eleventh House", theme: "House of Community", rules: "Friends, groups, hopes, wishes, humanitarian causes, social networks, future goals", naturalSign: "Aquarius" },
  { number: 12, name: "Twelfth House", theme: "House of the Unconscious", rules: "Subconscious, hidden enemies, isolation, karma, spirituality, endings, dreams, secrets", naturalSign: "Pisces" }
];

export const elements = [
  { name: "Fire", signs: ["Aries", "Leo", "Sagittarius"], qualities: "Passionate, dynamic, temperamental, enthusiastic, creative, inspirational", description: "Fire signs are known for their passion, energy, and spontaneity. They're natural leaders who inspire others with their enthusiasm and courage." },
  { name: "Earth", signs: ["Taurus", "Virgo", "Capricorn"], qualities: "Grounded, practical, reliable, sensual, material-focused, patient", description: "Earth signs are the builders of the zodiac, focused on creating tangible results. They're reliable, practical, and deeply connected to the physical world." },
  { name: "Air", signs: ["Gemini", "Libra", "Aquarius"], qualities: "Intellectual, communicative, social, analytical, objective, idealistic", description: "Air signs live in the realm of ideas and communication. They're intellectual, social, and driven by the exchange of thoughts and concepts." },
  { name: "Water", signs: ["Cancer", "Scorpio", "Pisces"], qualities: "Emotional, intuitive, sensitive, mysterious, nurturing, psychic", description: "Water signs navigate life through emotion and intuition. They're deeply sensitive, psychic, and connected to the invisible currents of feeling." }
];

export const modalities = [
  { name: "Cardinal", signs: ["Aries", "Cancer", "Libra", "Capricorn"], qualities: "Initiating, leading, active, enterprising, ambitious", description: "Cardinal signs mark the beginning of seasons and initiate action. They're the leaders and starters who set things in motion." },
  { name: "Fixed", signs: ["Taurus", "Leo", "Scorpio", "Aquarius"], qualities: "Stabilizing, determined, persistent, stubborn, powerful", description: "Fixed signs occur in the middle of seasons and maintain what's been started. They're determined, persistent, and provide stability." },
  { name: "Mutable", signs: ["Gemini", "Virgo", "Sagittarius", "Pisces"], qualities: "Adaptable, flexible, changeable, versatile, resourceful", description: "Mutable signs end seasons and prepare for change. They're adaptable, flexible, and comfortable with transformation." }
];

export const polarities = [
  { name: "Masculine (Yang)", signs: ["Aries", "Gemini", "Leo", "Libra", "Sagittarius", "Aquarius"], qualities: "Active, assertive, outward-focused, expressive, projective", description: "Masculine energy is outward-directed, active, and assertive. These signs tend to project energy outward and initiate action." },
  { name: "Feminine (Yin)", signs: ["Taurus", "Cancer", "Virgo", "Scorpio", "Capricorn", "Pisces"], qualities: "Receptive, reflective, inward-focused, nurturing, magnetic", description: "Feminine energy is inward-directed, receptive, and reflective. These signs tend to draw energy inward and respond to circumstances." }
];