export const chakraData = [
  {
    id: 'root',
    name: 'Root Chakra',
    sanskrit: 'Muladhara',
    color: '#EF4444',
    colorName: 'Red',
    location: 'Base of the spine, perineum',
    element: 'Earth',
    organs: ['Adrenal glands', 'Spine', 'Blood', 'Reproductive organs', 'Digestive system', 'Legs', 'Feet', 'Bones'],
    emotionalFunctions: ['Survival instincts', 'Security', 'Grounding', 'Stability', 'Physical identity', 'Trust in life'],
    balancedSigns: ['Feeling grounded and secure', 'Trusting in life', 'Physical vitality', 'Healthy relationship with money', 'Sense of belonging', 'Good physical health'],
    overactiveSigns: ['Greed and materialism', 'Resistance to change', 'Rigid boundaries', 'Hoarding behaviors', 'Excessive weight gain', 'Sluggishness'],
    underactiveSigns: ['Feeling ungrounded', 'Financial insecurity', 'Chronic fear and anxiety', 'Poor boundaries', 'Disconnection from body', 'Eating disorders'],
    emotionalManifestations: ['Fear', 'Anxiety', 'Nightmares', 'Feeling disconnected', 'Paranoia', 'Survival fears'],
    physicalManifestations: ['Lower back pain', 'Sciatica', 'Constipation', 'Immune disorders', 'Leg and feet issues', 'Eating disorders'],
    balancingMethods: ['Walking barefoot on earth', 'Gardening', 'Physical exercise', 'Red foods (beets, tomatoes)', 'Grounding meditation', 'Root vegetables', 'Nature walks', 'Drumming', 'Using red crystals like garnet or red jasper'],
    balanceIndicators: ['Feeling safe and secure', 'Trust in the universe', 'Physical energy and vitality', 'Healthy boundaries', 'Financial stability mindset', 'Strong sense of belonging']
  },
  {
    id: 'sacral',
    name: 'Sacral Chakra',
    sanskrit: 'Svadhisthana',
    color: '#F97316',
    colorName: 'Orange',
    location: 'Lower abdomen, below the navel',
    element: 'Water',
    organs: ['Reproductive organs', 'Kidneys', 'Bladder', 'Large intestine', 'Pelvis', 'Hips', 'Lower back'],
    emotionalFunctions: ['Creativity', 'Sexuality', 'Pleasure', 'Emotional flow', 'Intimacy', 'Passion', 'Joy'],
    balancedSigns: ['Healthy sexuality', 'Creative expression', 'Emotional intelligence', 'Ability to feel pleasure', 'Healthy boundaries in relationships', 'Passion for life'],
    overactiveSigns: ['Sexual addiction', 'Emotional volatility', 'Obsessive attachments', 'Manipulation through seduction', 'Excessive pleasure-seeking', 'Mood swings'],
    underactiveSigns: ['Low libido', 'Creative blocks', 'Emotional numbness', 'Fear of pleasure', 'Rigidity', 'Guilt around sexuality', 'Isolation'],
    emotionalManifestations: ['Guilt', 'Shame', 'Fear of intimacy', 'Emotional dependency', 'Jealousy', 'Creative frustration'],
    physicalManifestations: ['Reproductive issues', 'Urinary problems', 'Hip pain', 'Lower back pain', 'Sexual dysfunction', 'Kidney issues'],
    balancingMethods: ['Swimming or water activities', 'Hip-opening yoga poses', 'Orange foods (oranges, carrots)', 'Creative activities', 'Dance', 'Journaling emotions', 'Sensual self-care', 'Carnelian or orange calcite crystals'],
    balanceIndicators: ['Creative flow', 'Healthy emotional expression', 'Comfortable with intimacy', 'Joy in physical pleasures', 'Balanced sexuality', 'Emotional resilience']
  },
  {
    id: 'solar-plexus',
    name: 'Solar Plexus Chakra',
    sanskrit: 'Manipura',
    color: '#EAB308',
    colorName: 'Yellow',
    location: 'Upper abdomen, stomach area',
    element: 'Fire',
    organs: ['Digestive system', 'Stomach', 'Liver', 'Gallbladder', 'Pancreas', 'Spleen', 'Middle spine'],
    emotionalFunctions: ['Personal power', 'Self-esteem', 'Willpower', 'Confidence', 'Autonomy', 'Self-discipline'],
    balancedSigns: ['Strong sense of self', 'Confident decision-making', 'Healthy self-esteem', 'Good digestion', 'Ability to set boundaries', 'Personal empowerment'],
    overactiveSigns: ['Controlling behavior', 'Aggression', 'Perfectionism', 'Workaholism', 'Stubbornness', 'Need to dominate'],
    underactiveSigns: ['Low self-esteem', 'Indecisiveness', 'Victim mentality', 'Passivity', 'Poor digestion', 'Lack of direction'],
    emotionalManifestations: ['Shame', 'Powerlessness', 'Anger issues', 'Need for approval', 'Fear of rejection', 'Self-doubt'],
    physicalManifestations: ['Digestive issues', 'Ulcers', 'Diabetes', 'Eating disorders', 'Chronic fatigue', 'Liver problems'],
    balancingMethods: ['Core-strengthening exercises', 'Sunlight exposure', 'Yellow foods (bananas, lemons)', 'Setting healthy boundaries', 'Affirmations', 'Power poses', 'Citrine or tiger\'s eye crystals', 'Breath of fire pranayama'],
    balanceIndicators: ['Confidence in decisions', 'Healthy boundaries', 'Strong sense of purpose', 'Good digestion', 'Inner strength', 'Balanced ego']
  },
  {
    id: 'heart',
    name: 'Heart Chakra',
    sanskrit: 'Anahata',
    color: '#22C55E',
    colorName: 'Green',
    location: 'Center of chest',
    element: 'Air',
    organs: ['Heart', 'Lungs', 'Circulatory system', 'Arms', 'Hands', 'Thymus gland', 'Immune system'],
    emotionalFunctions: ['Love', 'Compassion', 'Forgiveness', 'Empathy', 'Connection', 'Self-love', 'Acceptance'],
    balancedSigns: ['Unconditional love', 'Compassion for self and others', 'Healthy relationships', 'Emotional openness', 'Forgiveness', 'Inner peace'],
    overactiveSigns: ['Codependency', 'Jealousy', 'Poor boundaries in relationships', 'People pleasing', 'Giving too much', 'Possessiveness'],
    underactiveSigns: ['Fear of intimacy', 'Isolation', 'Bitterness', 'Inability to forgive', 'Lack of empathy', 'Self-criticism'],
    emotionalManifestations: ['Grief', 'Loneliness', 'Resentment', 'Fear of betrayal', 'Difficulty trusting', 'Conditional love'],
    physicalManifestations: ['Heart problems', 'Lung issues', 'Breast cancer', 'Upper back pain', 'Arm and hand issues', 'Circulation problems'],
    balancingMethods: ['Heart-opening yoga poses', 'Green foods (leafy greens)', 'Loving-kindness meditation', 'Spending time in nature', 'Acts of kindness', 'Rose quartz or green aventurine crystals', 'Breathwork', 'Gratitude practice'],
    balanceIndicators: ['Open to giving and receiving love', 'Compassionate', 'Forgiving', 'Peaceful relationships', 'Self-love', 'Emotional balance']
  },
  {
    id: 'throat',
    name: 'Throat Chakra',
    sanskrit: 'Vishuddha',
    color: '#06B6D4',
    colorName: 'Blue',
    location: 'Throat, neck',
    element: 'Ether/Space',
    organs: ['Throat', 'Thyroid', 'Parathyroid', 'Mouth', 'Teeth', 'Gums', 'Neck', 'Shoulders', 'Ears'],
    emotionalFunctions: ['Communication', 'Self-expression', 'Truth', 'Authenticity', 'Listening', 'Creative expression'],
    balancedSigns: ['Clear communication', 'Authentic self-expression', 'Active listening', 'Speaking truth', 'Creative voice', 'Expressing needs clearly'],
    overactiveSigns: ['Excessive talking', 'Gossiping', 'Interrupting others', 'Dominating conversations', 'Inability to listen', 'Harsh words'],
    underactiveSigns: ['Fear of speaking', 'Difficulty expressing feelings', 'Shyness', 'Poor communication', 'Keeping secrets', 'Fear of judgment'],
    emotionalManifestations: ['Fear of speaking up', 'Inability to express emotions', 'Dishonesty', 'Social anxiety', 'Fear of being judged', 'Creative blocks'],
    physicalManifestations: ['Sore throat', 'Thyroid issues', 'Neck pain', 'Hearing problems', 'TMJ', 'Dental issues', 'Voice problems'],
    balancingMethods: ['Singing or chanting', 'Blue foods (blueberries)', 'Journaling', 'Honest conversations', 'Neck stretches', 'Blue lace agate or aquamarine crystals', 'Speaking affirmations aloud', 'Active listening practice'],
    balanceIndicators: ['Speaking truth with compassion', 'Creative expression flows', 'Good listener', 'Authentic communication', 'Clear voice', 'Healthy boundaries in speech']
  },
  {
    id: 'third-eye',
    name: 'Third Eye Chakra',
    sanskrit: 'Ajna',
    color: '#6366F1',
    colorName: 'Indigo',
    location: 'Forehead, between the eyebrows',
    element: 'Light',
    organs: ['Brain', 'Eyes', 'Ears', 'Nose', 'Pituitary gland', 'Pineal gland', 'Neurological system'],
    emotionalFunctions: ['Intuition', 'Wisdom', 'Insight', 'Imagination', 'Clarity', 'Perception', 'Vision'],
    balancedSigns: ['Strong intuition', 'Clear thinking', 'Good memory', 'Vivid imagination', 'Ability to visualize', 'Wisdom in decisions'],
    overactiveSigns: ['Nightmares', 'Hallucinations', 'Obsessive thinking', 'Difficulty concentrating', 'Living in fantasy', 'Disconnection from reality'],
    underactiveSigns: ['Poor intuition', 'Lack of imagination', 'Difficulty visualizing', 'Memory problems', 'Denial', 'Inability to see bigger picture'],
    emotionalManifestations: ['Confusion', 'Lack of clarity', 'Difficulty trusting intuition', 'Closed-mindedness', 'Excessive skepticism', 'Illusions'],
    physicalManifestations: ['Headaches', 'Eye strain', 'Vision problems', 'Sinus issues', 'Insomnia', 'Hormone imbalances', 'Learning disabilities'],
    balancingMethods: ['Meditation focusing on third eye', 'Purple foods (grapes, eggplant)', 'Dream journaling', 'Visualization practices', 'Reducing screen time', 'Amethyst or lapis lazuli crystals', 'Stargazing', 'Intuition exercises'],
    balanceIndicators: ['Clear intuition', 'Vivid dreams', 'Mental clarity', 'Good memory', 'Open to new ideas', 'Trust in inner wisdom']
  },
  {
    id: 'crown',
    name: 'Crown Chakra',
    sanskrit: 'Sahasrara',
    color: '#A855F7',
    colorName: 'Violet/White',
    location: 'Top of the head',
    element: 'Cosmic Energy/Thought',
    organs: ['Brain', 'Nervous system', 'Pineal gland', 'Muscular system', 'Skeletal system'],
    emotionalFunctions: ['Spiritual connection', 'Enlightenment', 'Unity consciousness', 'Divine wisdom', 'Transcendence', 'Bliss'],
    balancedSigns: ['Spiritual awareness', 'Sense of peace', 'Connection to higher self', 'Open-mindedness', 'Living with purpose', 'Feeling connected to all'],
    overactiveSigns: ['Spiritual addiction', 'Disconnection from body', 'Superiority complex', 'Obsession with spirituality', 'Neglecting earthly responsibilities', 'Escapism'],
    underactiveSigns: ['Spiritual disconnection', 'Cynicism', 'Closed-mindedness', 'Fear of death', 'Lack of purpose', 'Depression', 'Feeling alone in universe'],
    emotionalManifestations: ['Spiritual crisis', 'Lack of faith', 'Existential anxiety', 'Feeling disconnected from source', 'Materialism', 'Spiritual bypassing'],
    physicalManifestations: ['Migraines', 'Sensitivity to light', 'Neurological disorders', 'Chronic fatigue', 'Mental health issues', 'Sleep disorders'],
    balancingMethods: ['Silent meditation', 'Prayer', 'Fasting', 'Spending time in silence', 'Violet or white foods', 'Clear quartz or amethyst crystals', 'Connecting with nature', 'Acts of service', 'Studying spiritual texts'],
    balanceIndicators: ['Inner peace', 'Sense of oneness', 'Trust in divine plan', 'Living with purpose', 'Spiritual awareness', 'Gratitude for life']
  }
];

// Chakra thumbnail images
export const chakraThumbnails = {
  'crown': 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69894b94180b4131b2f82c0b/7369f5791_Gemini_Generated_Image_wimudtwimudtwimu.png',
  'third-eye': 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69894b94180b4131b2f82c0b/68467f41f_Gemini_Generated_Image_u56sgou56sgou56s.png',
  'throat': 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69894b94180b4131b2f82c0b/0a572ddf0_Gemini_Generated_Image_vcasv5vcasv5vcas1.png',
  'heart': 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69894b94180b4131b2f82c0b/c97199045_Gemini_Generated_Image_lnporjlnporjlnpo.png',
  'solar-plexus': 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69894b94180b4131b2f82c0b/40306d908_Gemini_Generated_Image_m3pg7am3pg7am3pg.png',
  'sacral': 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69894b94180b4131b2f82c0b/afceadcd9_Gemini_Generated_Image_tawzddtawzddtawz.png',
  'root': 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69894b94180b4131b2f82c0b/521cd67c4_Gemini_Generated_Image_x8sgvux8sgvux8sg.png'
};

export const getChakraById = (id) => chakraData.find(c => c.id === id);
export const getChakraByIndex = (index) => chakraData[index];
export const getChakraThumbnail = (id) => chakraThumbnails[id] || null;